name: Pull Reqest example 

on:
  pull_request:
    branches: 
      - main
    paths: #whitelist a set of files that we only want this to run where there is a change in that parcitular folder/files
      - typescript-project/**

  workflow_dispatch: 

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: typescript-project

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "npm" # cache npm between jobs
          cache-dependency-path: typescript-project/yarn.lock
        
      # Install yarn
      - name: Install Yarn
        run: npm install -g yarn

      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run linting
        run: yarn lint

      - name: Build the project
        run: yarn build

      # Run tests
      - name: Run tests
        run: yarn test

      

          
          
